import small from './images/Zazu.jpg';
import corky from './images/Kerio.jpg';
import ordinary from './images/Carousel.jpg';
import shtamb from './images/Indigoletta.jpg';

export const roses = [
  {
    img: shtamb,
    id: 1,
    name: 'name',
    type: 'Штамбові',
    price: 500,
  },
  {
    img: corky,
    id: 2,
    name: 'name',
    type: 'Плетисті',
    price: 45,
  },
  {
    img: small,
    id: 3,
    name: 'name',
    type: 'Дрібноквіткові',
    price: 35,
  },
  {
    img: ordinary,
    id: 4,
    name: 'name',
    type: 'Чайно гібридні',
    price: 35,
  },
  {
    img: corky,
    id: 5,
    name: 'name',
    type: 'Плетисті',
    price: 45,
  },
  {
    img: shtamb,
    id: 6,
    name: 'name',
    type: 'Штамбові',
    price: 500,
  },
  {
    img: ordinary,
    id: 7,
    name: 'name',
    type: 'Чайно гібридні',
    price: 35,
  },
  {
    img: small,
    id: 8,
    name: 'name',
    type: 'Дрібноквіткові',
    price: 35,
  },
  {
    img: corky,
    id: 9,
    name: 'name',
    type: 'Плетисті',
    price: 45,
  },
  {
    img: small,
    id: 10,
    name: 'name',
    type: 'Дрібноквіткові',
    price: 35,
  },
  {
    img: corky,
    id: 11,
    name: 'name',
    type: 'Плетисті',
    price: 45,
  },
  {
    img: shtamb,
    id: 12,
    name: 'name',
    type: 'Штамбові',
    price: 500,
  },
  {
    img: small,
    id: 13,
    name: 'name',
    type: 'Дрібноквіткові',
    price: 35,
  },
  {
    img: corky,
    id: 14,
    name: 'name',
    type: 'Плетисті',
    price: 45,
  },
  {
    img: ordinary,
    id: 15,
    name: 'name',
    type: 'Чайно гібридні',
    price: 35,
  },
  {
    img: small,
    id: 16,
    name: 'name',
    type: 'Дрібноквіткові',
    price: 35,
  },
  {
    img: corky,
    id: 17,
    name: 'name',
    type: 'Плетисті',
    price: 45,
  },
  {
    img: shtamb,
    id: 18,
    name: 'name',
    type: 'Штамбові',
    price: 500,
  },
  {
    img: small,
    id: 19,
    name: 'name',
    type: 'Дрібноквіткові',
    price: 35,
  },
  {
    img: ordinary,
    id: 20,
    name: 'name',
    type: 'Чайно гібридні',
    price: 35,
  },
];
